version: 2

jobs:
  build_and_test:
    docker:
      - image: anshulguleria/ubuntu-node-mongo:latest
        command: [mongod, --smallfiles]
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Running tests
          command: npm test
  push:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            make pull
            make build
            make push
  staging:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3e:be:05:27:97:c4:1c:8e:6b:0e:a5:ed:2e:bf:aa:4f"
      - run: ssh root@82.223.82.41 "bash -ic deploy-web-staging"
  production:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3e:be:05:27:97:c4:1c:8e:6b:0e:a5:ed:2e:bf:aa:4f"
      - run: ssh root@82.223.82.41 "bash -ic deploy-web-production"

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_and_test
      - push:
          requires:
            - build_and_test
          filters:
            branches:
              only: dev
      - staging:
          requires:
            - push
          filters:
            branches:
              only: dev
      - production:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
